### ISSUE TITLE
Clarity needed about what is happening when 2 different data types are compared

### ISSUE THREAD

**Issue by hansenjl** [learn-co-curriculum/python-numbers-and-booleans#7]
The following example makes it seem as if it does work well to simply compare different object types. 

```
"34th street" < 22
# False
```

The next instruction says "Well, now we know for sure (referring to if it works correctly). So, if we want to help our restaurant with deliveries, we should convert from a string to a number and then make the comparison."  This could be confusing because it's as if it's saying, "now we know that it works perfectly as expected but let's still convert it without an explanation as to why we should convert it".  It would be helpful to show an example of 2 different data types being compared that give an unexpected response and an explanation as to why. Such as `"5" > 9 # True` or even using "19th street".

**Comment by DavidAlberici** [comment]
This is a mistake, the point they are trying to make is that you CANNOT compare str to numbers (int or float). You can try it yourself in the next lessons. (I suppose you realized this long ago, but I am answering for future readers :) )
I pasted an example below, a simple line of code comparing a str to an int, you can see it throws a TypeError.
![image](https://user-images.githubusercontent.com/33468888/54690602-ac63d480-4b19-11e9-95ab-f2165d53ad6a.png)

**Comment by mas16** [comment]
It seems that this was an artifact of using Python 2 which allowed str and int boolean comparisons with numeric values evaluating to be less than str values. I have updated the kernel to Python 3 and made a note that a str and int comparison results in a type error.
