### ISSUE TITLE
Possible mistake

### ISSUE THREAD

**Issue by timsennett** [learn-co-curriculum/python-numbers-and-booleans#8]
The example on this page (specifically, the one below the question, "Does it make sense for a string or text to answer whether it is less than or greater than a number?") shows an output of False. Isn't it supposed to be a Syntax Error or Traceback? Apologies if I'm mistaken.
![Screen Shot 2019-08-05 at 2 53 43 PM](https://user-images.githubusercontent.com/51684970/62487846-dd733780-b790-11e9-8728-1677346e923b.png)

**Comment by mas16** [comment]
Thanks for flagging! Turns out this was originally written using a Python 2 kernel which allowed str and int comparisons. I have updated the kernel to Python 3 and it now evaluates to a TypeError. I also added a note in the text to explain that you cannot compare str and int
