### ISSUE TITLE
Update for example "34th street" < 22

### ISSUE THREAD

**Issue by joelachance** [learn-co-curriculum/python-numbers-and-booleans#9]
This gives us a TypeError, specifically: `TypeError: '<' not supported between instances of 'str' and 'int'`, instead of `False`. 

Coming from Javascript, `'34' < 22` _is_ actually `false`, since our string is coerced to an int. It might be worth pointing out Python doesn't give us type coercion when using arithmetic operators (unless this is too deep for a beginner's lesson) :)

**Comment by mas16** [comment]
Thanks for flagging the issue! It turns out this was originally written using a python 2 kernel which did allow str and int comparisons. I changed the kernel to python 3 and it now evaluates to TypeError. I also added a short explanatory note in the text.
